services:
  - type: web
    name: huddlace-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_HTTPS
        value: false
      - key: CORS_ORIGIN
        value: "https://huddlance.com,https://www.huddlance.com"
